FROM tpires/neo4j
MAINTAINER Paul Horn <phorn@avantgarde-labs.de>

# Add config and plugin
ADD neo4j-server.properties /var/lib/neo4j/conf/neo4j-server.properties
ADD dswarm-graph-assembly.jar /var/lib/neo4j/plugins/dswarm-graph.jar
