FROM martinseeler/oracle-server-jre
MAINTAINER Paul Horn <phorn@avantgarde-labs.de>

ADD dswarm.jar /app/dswarm.jar
ADD dswarm.conf /app/dswarm.conf
ADD create_database.sql /app/create_database.sql
ADD functions.sql /app/functions.sql
ADD init_internal_schema.sql /app/init_internal_schema.sql
ADD schema.sql /app/schema.sql

